name: Nuget Prerelease

on:
  push:
    tags:
      - prerelease-v*

jobs:
  pushprerelease:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9
      - uses: olegtarasov/get-tag@v2.1
        id: tagMaKoDateTimeConverter
        with:
          tagRegex: "prerelease-v(\\d+\\.\\d+\\.\\d+)"
      - name: copy README.md to package folder
        run: cp README.md MaKoDateTimeConverter/MaKoDateTimeConverter/README.md
      - name: Build/Check for compile errors (dotnet build)
        working-directory: "MaKoDateTimeConverter"
        run: dotnet build --configuration Release
      - name: Run Unit Tests (dotnet test)
        working-directory: "MaKoDateTimeConverter"
        run: dotnet test --configuration Release
      - name: Create Package MaKoDateTimeConverter (dotnet pack)
        working-directory: "MaKoDateTimeConverter/MaKoDateTimeConverter"
        run: dotnet pack MaKoDateTimeConverter.csproj --configuration Release -p:PackageVersion="${{ steps.tagMaKoDateTimeConverter.outputs.tag }}-beta${{ steps.current-time.outputs.formattedTime }}"
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Nuget push MaKoDateTimeConverter (prerelease)
        working-directory: "MaKoDateTimeConverter/MaKoDateTimeConverter"
        run: |
          nuget setApiKey ${{ secrets.NUGET_ORG_PUSH_TOKEN }}
          nuget push .\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -NoSymbols
